### ISSUE TITLE
Using kite.js in the browser Error?!

### ISSUE THREAD

**Issue by schmitch** [koding/kite.js#19]
Hello, I tried to use kite.js in the browser, but I always get the same error at kite-bundle.js:3045 that Promise.method is a undefined function.

**Comment by gokmen** [comment]
Hi @schmitch

Can u provide more details, how are you using, what are you trying to achieve, a simple code piece maybe?

**Comment by schmitch** [comment]
Hello, currently I just try to make it work.

put a simple index.html file which contains nothing more than

```
<!DOCTYPE html>
<html>

<head>
    <title>Demo</title>
    <script type="text/javascript" src="./kite-promises-bundle.js"></script>
    <script type="text/javascript">

    </script>
</head>

<body>
</body>

</html>
```
and put that into nginx or another webserver while kite-promises-bundle.js and kite-bundle.js lies inside the same directory of index.html.
Just wanted to have a quick demo

**Comment by gokmen** [comment]
Can u try this instead? https://github.com/koding/kite.js/blob/master/static/playground/kite-promises.html I'll update examples and README soon.

**Comment by schmitch** [comment]
Oh, that works thanks, just trying to get a complete example with a go backend now, still thanks, didn't see the vendor folder..
