### ISSUE TITLE
Where can I download kite-bundle.js file?

### ISSUE THREAD

**Issue by cenkalti** [koding/kite.js#20]

**Comment by cenkalti** [comment]
It should be useful to provide compiled kite-bundle.js and kontrol-bundle.js files in releases section.

**Comment by memiux** [comment]
:+1: Totally

**Comment by sinan** [comment]
Thanks for the suggestion, added the build output to the latest release: https://github.com/koding/kite.js/releases/tag/0.5.1 :package:
